#+TITLE:ヒミツのドキドキおとまりかい！
#+AUTHOR:CrinklyFriend
#+EMAIL:thingywhat@gmail.com

* owo wats this
This is a translation of one of Wadorigi's Diaper Doujins known as 「ヒミツのドキドキおとまりかい！」!

To be honest, the primary purpose of this is to get better at translating things, so it might not be very good (and might not even get finished!)--but I do have an end goal of making some doujins easier to read by people who can read English if it ever does get finished! So if you see problems, feel free to open an issue or pull request~

If this translation ever gets good enough, I'm even cool with Wadorigi taking my translations and releasing English versions of his stuff!

* Where's the doujin?
Out of respect for the artist, I won't be uploading the doujin itself--though if you would like to try to get your own copy, you can likely ask [[https://twitter.com/Jira_hosi][Wadorigi]] himself about it..! (This is a link to his AD, since I'm not sure he wants to talk about things like that on main all the time)

Alternatively, these books show up at [[https://www.comiket.co.jp/][Comiket]] and [[http://skypalette.jp/kemoket/][Kemoket]] reasonably often, so you can also commission someone to go in your stead to pick you up a book.

These are the two best ways to get this doujin in ways that shouldn't be harmful to the artist. (It's tricky when you're a foreigner and want to read these things, since we can do so many things that can get artists in trouble D:)

Either way, good luck~

* Where's the translation?
With all of this in mind, [[./translation.org][here is my as-of-yet incomplete attempt to translate Wadorigi's new doujin..!]]
